name: RSpec
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: sidekiq
          POSTGRES_PASSWORD: benchmark
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: SCM
        uses: actions/checkout@v1
      - name: Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Library
        run: sudo apt-get install libpq-dev
      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 10 --retry 10
      - name: Secrets
        run: |
          echo $RAILS_MASTER_KEY > config/credentials/github.key
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      - name: Migration
        run: |
          bundle exec rails db:create db:migrate
        env:
          RAILS_ENV: github
      - name: RSpec
        run: |
          bundle exec rspec --format d
        env:
          RAILS_ENV: github
